version: '3.9'
services:
  postgres:
    env_file: ./.env
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
<<<<<<< HEAD
      - ./pgdata:/var/lib/postgresql/data/pgdata
=======
      - pgdata:/var/lib/postgresql/data/pgdata
>>>>>>> 3ed39eb (initial commit)

volumes:
  pgdata:
